name: CI/CD with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: actions/checkout@v4

      - name: Logga in på Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build
        run: docker build . -t attaponsayod/attapon:${{ github.sha }}

      - name: Deploy
        run: docker push attaponsayod/attapon:${{ github.sha }}